import fs from "fs";
import path from "path";
import { BikeProduct, BikeProductSchema, Discipline, FrameMaterial, ForkMaterial, GroupsetBrand } from "../src/lib/schema/bike";

const CARRETERA_FILE = path.join(process.cwd(), "data", "bikes", "carretera.json");
const GRAVEL_FILE = path.join(process.cwd(), "data", "bikes", "gravel.json");
const MONTANA_FILE = path.join(process.cwd(), "data", "bikes", "montana.json");
const ORBEA_LINKS_FILE = path.join(process.cwd(), "links", "orbea.txt");

function calculateRatios(chainrings: string, cassette: string) {
  const rings = chainrings
    .replace(/T/gi, "")
    .split(/[\/\-]/)
    .map((r) => parseFloat(r.trim()))
    .filter((n) => !isNaN(n) && n > 0 && n < 70);

  const cogs = cassette
    .replace(/T/gi, "")
    .split(/[\/\-xX]/)
    .map((c) => parseFloat(c.trim()))
    .filter((n) => !isNaN(n) && n > 0 && n < 70);

  const minRing = Math.min(...(rings.length > 0 ? rings : [34]));
  const maxRing = Math.max(...(rings.length > 0 ? rings : [50]));
  const minCog = Math.min(...(cogs.length > 0 ? cogs : [11]));
  const maxCog = Math.max(...(cogs.length > 0 ? cogs : [34]));

  let minRatio = Number((minRing / maxCog).toFixed(2));
  let maxRatio = Number((maxRing / minCog).toFixed(2));

  return { minRatio, maxRatio };
}

interface OrbeaModelDef {
  idSlug: string;
  modelName: string;
  family: string;
  year: number;
  discipline: Discipline;
  categoryFile: "carretera" | "gravel" | "montana";
  price: number;
  originalMsrp?: number;
  frameMaterial: FrameMaterial;
  forkMaterial: ForkMaterial;
  weightKg?: number;
  clearanceMm: number;
  integratedCockpit: boolean;
  bikepackingMounts: boolean;
  groupset: {
    brand: GroupsetBrand;
    name: string;
    isElectronic: boolean;
    speedCount: number;
    chainrings: string;
    cassette: string;
  };
  geometry: {
    stackMm: number;
    reachMm: number;
    headTubeAngleDeg: number;
    chainstayLengthMm: number;
    seatTubeAngleDeg?: number;
    topTubeLengthMm?: number;
    seatTubeLengthMm?: number;
    headTubeLengthMm?: number;
    wheelbaseMm?: number;
    bbDropMm?: number;
  };
  cuadroDesc: string;
  horquillaDesc: string;
  frenosDesc: string;
  ruedasDesc: string;
  cubiertasDesc: string;
  manillarDesc: string;
  potenciaDesc: string;
  tijaDesc: string;
  sillinDesc: string;
  officialUrl: string;
  officialImageUrl: string;
}

const ORBEA_MODELS: OrbeaModelDef[] = [
  // ==========================================
  // CARRETERA - ORCA (Escaladora / Ligera)
  // ==========================================
  {
    idSlug: "orbea-orca-m10iltd-2025",
    modelName: "Orca M10iLTD",
    family: "Orca",
    year: 2025,
    discipline: "road_race",
    categoryFile: "carretera",
    price: 10999,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 6.7,
    clearanceMm: 32,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano Dura-Ace Di2 R9200",
      isElectronic: true,
      speedCount: 12,
      chainrings: "36/52T",
      cassette: "11-30T",
    },
    geometry: {
      stackMm: 550,
      reachMm: 385,
      headTubeAngleDeg: 72.8,
      chainstayLengthMm: 408,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 548,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 140,
      wheelbaseMm: 980,
      bbDropMm: 70,
    },
    cuadroDesc: "Orbea Orca carbon OMX Disc, monocoque construction, HS 1,5, BB 386 EVO, thru axle 12x142mm",
    horquillaDesc: "Orbea Orca OMX ICR fork 2024, full carbon, 1-1/8 - 1,5 tapared head tube compatible, thru axle 12x100mm",
    frenosDesc: "Shimano R9270 Hydraulic Disc",
    ruedasDesc: "Oquo Road Performance RP45LTD Carbon Tubeless Ready",
    cubiertasDesc: "Vittoria Corsa Speed G2.0 TLR 700x28c",
    manillarDesc: "OC Road Performance RP11 Carbon, Reach 80, Drop 125, with Di2 hole",
    potenciaDesc: "OC Road Performance RP10, -8º",
    tijaDesc: "OC Performance XP10-S Carbon, 27.2mm, Setback 20",
    sillinDesc: "Fizik Vento Antares R1 Carbon 140mm",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/orca/cat/orca-m10iltd-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-orca-m20iltd-2025",
    modelName: "Orca M20iLTD",
    family: "Orca",
    year: 2025,
    discipline: "road_race",
    categoryFile: "carretera",
    price: 6999,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 7.2,
    clearanceMm: 32,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano Ultegra Di2 R8100",
      isElectronic: true,
      speedCount: 12,
      chainrings: "34/50T",
      cassette: "11-30T",
    },
    geometry: {
      stackMm: 550,
      reachMm: 385,
      headTubeAngleDeg: 72.8,
      chainstayLengthMm: 408,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 548,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 140,
      wheelbaseMm: 980,
      bbDropMm: 70,
    },
    cuadroDesc: "Orbea Orca carbon OMX Disc, monocoque, HS 1,5, BB 386 EVO, thru axle 12x142mm",
    horquillaDesc: "Orbea Orca OMX ICR fork, full carbon, 12x100mm",
    frenosDesc: "Shimano R8170 Hydraulic Disc",
    ruedasDesc: "Oquo Road Performance RP45TEAM Carbon Tubeless Ready",
    cubiertasDesc: "Vittoria Corsa Pro G2.0 TLR 700x28c",
    manillarDesc: "OC Road Performance RP11 Carbon",
    potenciaDesc: "OC Road Performance RP10, -8º",
    tijaDesc: "OC Performance XP10-S Carbon, 27.2mm",
    sillinDesc: "Fizik Vento Antares R3 k:ium",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/orca/cat/orca-m20iltd-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-orca-m21eltd-2025",
    modelName: "Orca M21eLTD",
    family: "Orca",
    year: 2025,
    discipline: "road_race",
    categoryFile: "carretera",
    price: 8799,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 7.0,
    clearanceMm: 32,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "sram",
      name: "SRAM Force AXS Power Meter",
      isElectronic: true,
      speedCount: 12,
      chainrings: "35/48T",
      cassette: "10-33T",
    },
    geometry: {
      stackMm: 550,
      reachMm: 385,
      headTubeAngleDeg: 72.8,
      chainstayLengthMm: 408,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 548,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 140,
      wheelbaseMm: 980,
      bbDropMm: 70,
    },
    cuadroDesc: "Orbea Orca carbon OMX Disc, monocoque, thru axle 12x142mm",
    horquillaDesc: "Orbea Orca OMX ICR fork, full carbon, 12x100mm",
    frenosDesc: "SRAM Force AXS Hydraulic Disc",
    ruedasDesc: "Oquo Road Performance RP45LTD Carbon Tubeless Ready",
    cubiertasDesc: "Vittoria Corsa Pro G2.0 TLR 700x28c",
    manillarDesc: "OC Road Performance RP11 Carbon",
    potenciaDesc: "OC Road Performance RP10, -8º",
    tijaDesc: "OC Performance XP10-S Carbon, 27.2mm",
    sillinDesc: "Fizik Vento Antares R1 Carbon",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/orca/cat/orca-m21eltd-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-orca-m20iteam-2025",
    modelName: "Orca M20iTEAM",
    family: "Orca",
    year: 2025,
    discipline: "road_race",
    categoryFile: "carretera",
    price: 4599,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 7.7,
    clearanceMm: 32,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano Ultegra Di2 R8100",
      isElectronic: true,
      speedCount: 12,
      chainrings: "34/50T",
      cassette: "11-30T",
    },
    geometry: {
      stackMm: 550,
      reachMm: 385,
      headTubeAngleDeg: 72.8,
      chainstayLengthMm: 408,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 548,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 140,
      wheelbaseMm: 980,
      bbDropMm: 70,
    },
    cuadroDesc: "Orbea Orca carbon OMR Disc, monocoque construction, HS 1,5, BB 386 EVO, thru axle 12x142mm",
    horquillaDesc: "Orbea Orca OMR ICR fork 2024, full carbon, 12x100mm",
    frenosDesc: "Shimano R8170 Hydraulic Disc",
    ruedasDesc: "Oquo Road Performance RP35TEAM Carbon Tubeless Ready",
    cubiertasDesc: "Vittoria Corsa N.Ext G2.0 Foldable 700x28c",
    manillarDesc: "OC Road Performance RP21 Alu SL, Reach 80, Drop 125",
    potenciaDesc: "OC Road Performance RP21, -6º",
    tijaDesc: "OC Performance XP10-S Carbon, 27.2mm",
    sillinDesc: "Fizik Vento Antares R5",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/orca/cat/orca-m20iteam-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-orca-m35i-2025",
    modelName: "Orca M35i",
    family: "Orca",
    year: 2025,
    discipline: "road_race",
    categoryFile: "carretera",
    price: 3799,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 8.1,
    clearanceMm: 32,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano 105 Di2 R7100",
      isElectronic: true,
      speedCount: 12,
      chainrings: "34/50T",
      cassette: "11-34T",
    },
    geometry: {
      stackMm: 550,
      reachMm: 385,
      headTubeAngleDeg: 72.8,
      chainstayLengthMm: 408,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 548,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 140,
      wheelbaseMm: 980,
      bbDropMm: 70,
    },
    cuadroDesc: "Orbea Orca carbon OMR Disc, monocoque, thru axle 12x142mm",
    horquillaDesc: "Orbea Orca OMR ICR fork, full carbon, 12x100mm",
    frenosDesc: "Shimano R7170 Hydraulic Disc",
    ruedasDesc: "Oquo Road Performance RP35PRO Carbon Tubeless Ready",
    cubiertasDesc: "Vittoria Rubino IV G2.0 Foldable 700x28c",
    manillarDesc: "OC Road Performance RP21 Alu SL",
    potenciaDesc: "OC Road Performance RP21, -6º",
    tijaDesc: "OC Performance XP10-S Carbon, 27.2mm",
    sillinDesc: "Fizik Aliante R5",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/orca/cat/orca-m35i-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-orca-m30i-2025",
    modelName: "Orca M30i",
    family: "Orca",
    year: 2025,
    discipline: "road_race",
    categoryFile: "carretera",
    price: 3399,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 8.3,
    clearanceMm: 32,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano 105 Di2 R7100",
      isElectronic: true,
      speedCount: 12,
      chainrings: "34/50T",
      cassette: "11-34T",
    },
    geometry: {
      stackMm: 550,
      reachMm: 385,
      headTubeAngleDeg: 72.8,
      chainstayLengthMm: 408,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 548,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 140,
      wheelbaseMm: 980,
      bbDropMm: 70,
    },
    cuadroDesc: "Orbea Orca carbon OMR Disc, monocoque, thru axle 12x142mm",
    horquillaDesc: "Orbea Orca OMR ICR fork, full carbon, 12x100mm",
    frenosDesc: "Shimano R7170 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 700c, 21c, 28H",
    cubiertasDesc: "Vittoria Zafiro V Rigid bead 700x28c",
    manillarDesc: "OC Road Performance RP31, Reach 80, Drop 125",
    potenciaDesc: "OC Road Performance RP21, -6º",
    tijaDesc: "Carbon, 27.2mm, Setback 20",
    sillinDesc: "Fizik Aliante R5",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/orca/cat/orca-m30i-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-orca-m30-2025",
    modelName: "Orca M30",
    family: "Orca",
    year: 2025,
    discipline: "road_race",
    categoryFile: "carretera",
    price: 2599,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 8.6,
    clearanceMm: 32,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano 105 R7100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "34/50T",
      cassette: "11-34T",
    },
    geometry: {
      stackMm: 550,
      reachMm: 385,
      headTubeAngleDeg: 72.8,
      chainstayLengthMm: 408,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 548,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 140,
      wheelbaseMm: 980,
      bbDropMm: 70,
    },
    cuadroDesc: "Orbea Orca carbon OMR Disc, monocoque construction, HS 1,5, BB 386 EVO, thru axle 12x142mm",
    horquillaDesc: "Orbea Orca OMR ICR fork, full carbon, 12x100mm",
    frenosDesc: "Shimano R7170 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 700c, 21c, 28H",
    cubiertasDesc: "Vittoria Zafiro V Rigid bead 700x28c",
    manillarDesc: "OC Road Performance RP31, Reach 80, Drop 125",
    potenciaDesc: "OC Road Performance RP21, -6º",
    tijaDesc: "Carbon, 27.2mm, Setback 20",
    sillinDesc: "Fizik Aliante R5",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/orca/cat/orca-m30-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },

  // ==========================================
  // CARRETERA - ORCA AERO (Aerodinámica Pura)
  // ==========================================
  {
    idSlug: "orbea-orca-aero-m10iltd-2025",
    modelName: "Orca Aero M10iLTD",
    family: "Orca Aero",
    year: 2025,
    discipline: "road_race",
    categoryFile: "carretera",
    price: 10499,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 7.4,
    clearanceMm: 30,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano Dura-Ace Di2 R9200",
      isElectronic: true,
      speedCount: 12,
      chainrings: "36/52T",
      cassette: "11-30T",
    },
    geometry: {
      stackMm: 546,
      reachMm: 388,
      headTubeAngleDeg: 72.8,
      chainstayLengthMm: 408,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 550,
      seatTubeLengthMm: 485,
      headTubeLengthMm: 138,
      wheelbaseMm: 980,
      bbDropMm: 70,
    },
    cuadroDesc: "Orbea Orca Aero Carbon OMX disc, monocoque construction, HS 1,5, BB 386 EVO, thru axle 12x142mm",
    horquillaDesc: "Orbea Orca Aero OMX ICR, full carbon, 1-1/8 - 1,5, thru axle 12x100mm",
    frenosDesc: "Shimano R9270 Hydraulic Disc",
    ruedasDesc: "Oquo Road Performance RP57LTD Carbon Tubeless Ready",
    cubiertasDesc: "Vittoria Corsa Pro TLR 700x28c",
    manillarDesc: "OC Road Aero RA10 Carbon, Reach 80, Drop 125",
    potenciaDesc: "OC Road Performance RP10, -8º",
    tijaDesc: "OC Road Aero AERO10 Carbon, Setback 0-25mm",
    sillinDesc: "Prologo Scratch M5 Nack Carbon 140mm",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/orca-aero/cat/orca-aero-m10iltd-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-orca-aero-m20iltd-2025",
    modelName: "Orca Aero M20iLTD",
    family: "Orca Aero",
    year: 2025,
    discipline: "road_race",
    categoryFile: "carretera",
    price: 6499,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 7.9,
    clearanceMm: 30,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano Ultegra Di2 R8100",
      isElectronic: true,
      speedCount: 12,
      chainrings: "36/52T",
      cassette: "11-30T",
    },
    geometry: {
      stackMm: 546,
      reachMm: 388,
      headTubeAngleDeg: 72.8,
      chainstayLengthMm: 408,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 550,
      seatTubeLengthMm: 485,
      headTubeLengthMm: 138,
      wheelbaseMm: 980,
      bbDropMm: 70,
    },
    cuadroDesc: "Orbea Orca Aero Carbon OMX disc, monocoque, thru axle 12x142mm",
    horquillaDesc: "Orbea Orca Aero OMX ICR, full carbon, 12x100mm",
    frenosDesc: "Shimano R8170 Hydraulic Disc",
    ruedasDesc: "Oquo Road Performance RP57TEAM Carbon Tubeless Ready",
    cubiertasDesc: "Vittoria Corsa N.Ext TLR 700x28c",
    manillarDesc: "OC Road Aero RA10 Carbon",
    potenciaDesc: "OC Road Performance RP10, -8º",
    tijaDesc: "OC Road Aero AERO10 Carbon",
    sillinDesc: "Prologo Scratch M5 T2.0",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/orca-aero/cat/orca-aero-m20iltd-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-orca-aero-m30iltd-2025",
    modelName: "Orca Aero M30iLTD",
    family: "Orca Aero",
    year: 2025,
    discipline: "road_race",
    categoryFile: "carretera",
    price: 4499,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 8.4,
    clearanceMm: 30,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano 105 Di2 R7100",
      isElectronic: true,
      speedCount: 12,
      chainrings: "36/52T",
      cassette: "11-34T",
    },
    geometry: {
      stackMm: 546,
      reachMm: 388,
      headTubeAngleDeg: 72.8,
      chainstayLengthMm: 408,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 550,
      seatTubeLengthMm: 485,
      headTubeLengthMm: 138,
      wheelbaseMm: 980,
      bbDropMm: 70,
    },
    cuadroDesc: "Orbea Orca Aero Carbon OMX disc, monocoque, thru axle 12x142mm",
    horquillaDesc: "Orbea Orca Aero OMX ICR, full carbon, 12x100mm",
    frenosDesc: "Shimano R7170 Hydraulic Disc",
    ruedasDesc: "Oquo Road Performance RP45PRO Carbon Tubeless Ready",
    cubiertasDesc: "Vittoria Rubino IV G2.0 Foldable 700x28c",
    manillarDesc: "OC Road Aero RA10 Carbon",
    potenciaDesc: "OC Road Performance RP10, -8º",
    tijaDesc: "OC Road Aero AERO10 Carbon",
    sillinDesc: "Prologo Dimension T4.0",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/orca-aero/cat/orca-aero-m30iltd-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },

  // ==========================================
  // CARRETERA - AVANT (Gran Fondo / Confort)
  // ==========================================
  {
    idSlug: "orbea-avant-h30-2025",
    modelName: "Avant H30",
    family: "Avant",
    year: 2025,
    discipline: "road_endurance",
    categoryFile: "carretera",
    price: 1799,
    frameMaterial: "aluminum",
    forkMaterial: "carbon",
    weightKg: 9.6,
    clearanceMm: 35,
    integratedCockpit: false,
    bikepackingMounts: true,
    groupset: {
      brand: "shimano",
      name: "Shimano 105 R7100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "34/50T",
      cassette: "11-34T",
    },
    geometry: {
      stackMm: 570,
      reachMm: 375,
      headTubeAngleDeg: 72.0,
      chainstayLengthMm: 415,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 545,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 165,
      wheelbaseMm: 995,
      bbDropMm: 72,
    },
    cuadroDesc: "Orbea Avant Hydro disc, hydroformed triple butted aluminum, HS 1,5 ICR, BB 68mm, thru axle 12x142mm",
    horquillaDesc: "Orbea carbon fork, full carbon, 1-1/8 - 1,5, thru axle 12x100mm",
    frenosDesc: "Shimano R7170 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 700c, 21c, 28H",
    cubiertasDesc: "Vittoria Zafiro V Rigid bead 700x28c",
    manillarDesc: "OC Road Performance RP31, Reach 80, Drop 125",
    potenciaDesc: "OC Road Performance RP21, -6º",
    tijaDesc: "Alloy, 27.2mm, Setback 20",
    sillinDesc: "Fizik Aliante R5",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/avant/cat/avant-h30-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-avant-h40-2025",
    modelName: "Avant H40",
    family: "Avant",
    year: 2025,
    discipline: "road_endurance",
    categoryFile: "carretera",
    price: 1399,
    frameMaterial: "aluminum",
    forkMaterial: "carbon",
    weightKg: 9.9,
    clearanceMm: 35,
    integratedCockpit: false,
    bikepackingMounts: true,
    groupset: {
      brand: "shimano",
      name: "Shimano Tiagra 4700",
      isElectronic: false,
      speedCount: 10,
      chainrings: "34/50T",
      cassette: "11-34T",
    },
    geometry: {
      stackMm: 570,
      reachMm: 375,
      headTubeAngleDeg: 72.0,
      chainstayLengthMm: 415,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 545,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 165,
      wheelbaseMm: 995,
      bbDropMm: 72,
    },
    cuadroDesc: "Orbea Avant Hydro disc, hydroformed triple butted aluminum, thru axle 12x142mm",
    horquillaDesc: "Orbea carbon fork, full carbon, 12x100mm",
    frenosDesc: "Shimano Tiagra 4770 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 700c, 21c, 28H",
    cubiertasDesc: "Vittoria Zafiro V Rigid bead 700x28c",
    manillarDesc: "OC Road Performance RP31",
    potenciaDesc: "OC Road Performance RP21, -6º",
    tijaDesc: "Alloy, 27.2mm, Setback 20",
    sillinDesc: "Fizik Aliante R5",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/carretera/avant/cat/avant-h40-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },

  // ==========================================
  // GRAVEL - TERRA (Aventura & Competición)
  // ==========================================
  {
    idSlug: "orbea-terra-m21eteam-2025",
    modelName: "Terra M21eTEAM",
    family: "Terra",
    year: 2025,
    discipline: "gravel",
    categoryFile: "gravel",
    price: 5799,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 8.4,
    clearanceMm: 45,
    integratedCockpit: true,
    bikepackingMounts: true,
    groupset: {
      brand: "sram",
      name: "SRAM Force XPLR AXS",
      isElectronic: true,
      speedCount: 12,
      chainrings: "40T",
      cassette: "10-44T",
    },
    geometry: {
      stackMm: 580,
      reachMm: 385,
      headTubeAngleDeg: 71.0,
      chainstayLengthMm: 420,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 555,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 155,
      wheelbaseMm: 1025,
      bbDropMm: 78,
    },
    cuadroDesc: "Orbea Terra carbon OMR Disc, monocoque construction, HS 1,5, LOCKR internal downtube storage, thru axle 12x142mm",
    horquillaDesc: "Orbea Terra OMR carbon disc fork, full carbon steerer, thru axle 12x100mm",
    frenosDesc: "SRAM Force AXS Hydraulic Disc",
    ruedasDesc: "Oquo Gravel Control GC25TEAM Carbon Tubeless Ready",
    cubiertasDesc: "Pirelli Cinturato Gravel H 700x40c TLR",
    manillarDesc: "OC Gravel GR31-R Carbon, Flare 12º, Drop 110",
    potenciaDesc: "OC Road Performance RP10, -8º",
    tijaDesc: "OC Performance XP10 Carbon, 27.2mm",
    sillinDesc: "Prologo Akero AGX STN 150mm",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/gravel/terra/cat/terra-m21eteam-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-terra-m20iteam-2025",
    modelName: "Terra M20iTEAM",
    family: "Terra",
    year: 2025,
    discipline: "gravel",
    categoryFile: "gravel",
    price: 5399,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 8.6,
    clearanceMm: 45,
    integratedCockpit: true,
    bikepackingMounts: true,
    groupset: {
      brand: "shimano",
      name: "Shimano GRX Di2 RX825",
      isElectronic: true,
      speedCount: 12,
      chainrings: "31/48T",
      cassette: "11-36T",
    },
    geometry: {
      stackMm: 580,
      reachMm: 385,
      headTubeAngleDeg: 71.0,
      chainstayLengthMm: 420,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 555,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 155,
      wheelbaseMm: 1025,
      bbDropMm: 78,
    },
    cuadroDesc: "Orbea Terra carbon OMR Disc, monocoque, LOCKR storage, thru axle 12x142mm",
    horquillaDesc: "Orbea Terra OMR carbon disc fork, full carbon, 12x100mm",
    frenosDesc: "Shimano RX820 Hydraulic Disc",
    ruedasDesc: "Oquo Gravel Control GC25TEAM Carbon Tubeless Ready",
    cubiertasDesc: "Pirelli Cinturato Gravel H 700x40c TLR",
    manillarDesc: "OC Gravel GR31-R Carbon, Flare 12º",
    potenciaDesc: "OC Road Performance RP10, -8º",
    tijaDesc: "OC Performance XP10 Carbon, 27.2mm",
    sillinDesc: "Prologo Akero AGX STN",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/gravel/terra/cat/terra-m20iteam-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-terra-m30team-2025",
    modelName: "Terra M30TEAM",
    family: "Terra",
    year: 2025,
    discipline: "gravel",
    categoryFile: "gravel",
    price: 3199,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 9.1,
    clearanceMm: 45,
    integratedCockpit: false,
    bikepackingMounts: true,
    groupset: {
      brand: "shimano",
      name: "Shimano GRX RX820 / RX610",
      isElectronic: false,
      speedCount: 12,
      chainrings: "30/46T",
      cassette: "11-36T",
    },
    geometry: {
      stackMm: 580,
      reachMm: 385,
      headTubeAngleDeg: 71.0,
      chainstayLengthMm: 420,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 555,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 155,
      wheelbaseMm: 1025,
      bbDropMm: 78,
    },
    cuadroDesc: "Orbea Terra carbon OMR Disc, monocoque construction, LOCKR downtube storage, thru axle 12x142mm",
    horquillaDesc: "Orbea Terra OMR carbon disc fork, full carbon, 12x100mm",
    frenosDesc: "Shimano RX400 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 700c, 21c, 28H",
    cubiertasDesc: "Vittoria Terreno Dry CX-Gravel G2.0 TNT 700x38c",
    manillarDesc: "OC Gravel GR31, Flare 12º, Reach 70, Drop 110",
    potenciaDesc: "OC Road Performance RP21, -6º",
    tijaDesc: "OC Performance XP10 Carbon, 27.2mm",
    sillinDesc: "Prologo Akero AGX STN 150mm",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/gravel/terra/cat/terra-m30team-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-terra-m30team-1x-2025",
    modelName: "Terra M30TEAM 1X",
    family: "Terra",
    year: 2025,
    discipline: "gravel",
    categoryFile: "gravel",
    price: 3099,
    frameMaterial: "carbon",
    forkMaterial: "carbon",
    weightKg: 8.9,
    clearanceMm: 45,
    integratedCockpit: false,
    bikepackingMounts: true,
    groupset: {
      brand: "shimano",
      name: "Shimano GRX RX820 1X",
      isElectronic: false,
      speedCount: 12,
      chainrings: "40T",
      cassette: "10-45T",
    },
    geometry: {
      stackMm: 580,
      reachMm: 385,
      headTubeAngleDeg: 71.0,
      chainstayLengthMm: 420,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 555,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 155,
      wheelbaseMm: 1025,
      bbDropMm: 78,
    },
    cuadroDesc: "Orbea Terra carbon OMR Disc, monocoque, LOCKR storage, thru axle 12x142mm",
    horquillaDesc: "Orbea Terra OMR carbon disc fork, full carbon, 12x100mm",
    frenosDesc: "Shimano RX400 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 700c, 21c, 28H",
    cubiertasDesc: "Vittoria Terreno Dry CX-Gravel G2.0 TNT 700x38c",
    manillarDesc: "OC Gravel GR31, Flare 12º",
    potenciaDesc: "OC Road Performance RP21, -6º",
    tijaDesc: "OC Performance XP10 Carbon, 27.2mm",
    sillinDesc: "Prologo Akero AGX STN 150mm",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/gravel/terra/cat/terra-m30team-1x-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-terra-h30-2025",
    modelName: "Terra H30",
    family: "Terra",
    year: 2025,
    discipline: "gravel",
    categoryFile: "gravel",
    price: 2299,
    frameMaterial: "aluminum",
    forkMaterial: "carbon",
    weightKg: 9.9,
    clearanceMm: 45,
    integratedCockpit: false,
    bikepackingMounts: true,
    groupset: {
      brand: "shimano",
      name: "Shimano GRX RX820 / RX610",
      isElectronic: false,
      speedCount: 12,
      chainrings: "30/46T",
      cassette: "11-36T",
    },
    geometry: {
      stackMm: 580,
      reachMm: 385,
      headTubeAngleDeg: 71.0,
      chainstayLengthMm: 420,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 555,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 155,
      wheelbaseMm: 1025,
      bbDropMm: 78,
    },
    cuadroDesc: "Orbea Terra Hydro disc, hydroformed triple butted aluminum, HS 1,5 ICR, thru axle 12x142mm",
    horquillaDesc: "Orbea Terra OMR carbon disc fork, full carbon, 12x100mm",
    frenosDesc: "Shimano RX400 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 700c, 21c, 28H",
    cubiertasDesc: "Vittoria Terreno Dry CX-Gravel G2.0 TNT 700x38c",
    manillarDesc: "OC Gravel GR31, Flare 12º",
    potenciaDesc: "OC Road Performance RP21, -6º",
    tijaDesc: "Alloy, 27.2mm, Setback 0",
    sillinDesc: "Prologo Akero AGX STN",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/gravel/terra/cat/terra-h30-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-terra-h40-2025",
    modelName: "Terra H40",
    family: "Terra",
    year: 2025,
    discipline: "gravel",
    categoryFile: "gravel",
    price: 1899,
    frameMaterial: "aluminum",
    forkMaterial: "carbon",
    weightKg: 10.3,
    clearanceMm: 45,
    integratedCockpit: false,
    bikepackingMounts: true,
    groupset: {
      brand: "shimano",
      name: "Shimano GRX RX400",
      isElectronic: false,
      speedCount: 10,
      chainrings: "30/46T",
      cassette: "11-36T",
    },
    geometry: {
      stackMm: 580,
      reachMm: 385,
      headTubeAngleDeg: 71.0,
      chainstayLengthMm: 420,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 555,
      seatTubeLengthMm: 490,
      headTubeLengthMm: 155,
      wheelbaseMm: 1025,
      bbDropMm: 78,
    },
    cuadroDesc: "Orbea Terra Hydro disc, hydroformed triple butted aluminum, thru axle 12x142mm",
    horquillaDesc: "Orbea Terra OMR carbon disc fork, full carbon, 12x100mm",
    frenosDesc: "Shimano RX400 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 700c, 21c, 28H",
    cubiertasDesc: "Vittoria Terreno Dry CX-Gravel G2.0 TNT 700x38c",
    manillarDesc: "OC Gravel GR31, Flare 12º",
    potenciaDesc: "OC Road Performance RP21, -6º",
    tijaDesc: "Alloy, 27.2mm, Setback 0",
    sillinDesc: "Prologo Akero AGX STN",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/gravel/terra/cat/terra-h40-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },

  // ==========================================
  // MONTAÑA - OIZ (XC Doble Suspensión 120mm)
  // ==========================================
  {
    idSlug: "orbea-oiz-m-ltd-2025",
    modelName: "Oiz M-LTD",
    family: "Oiz",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 10499,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 9.9,
    clearanceMm: 62,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "sram",
      name: "SRAM XX SL Eagle AXS Transmission",
      isElectronic: true,
      speedCount: 12,
      chainrings: "34T",
      cassette: "10-52T",
    },
    geometry: {
      stackMm: 605,
      reachMm: 450,
      headTubeAngleDeg: 67.0,
      chainstayLengthMm: 432,
      seatTubeAngleDeg: 76.5,
      topTubeLengthMm: 598,
      seatTubeLengthMm: 432,
      headTubeLengthMm: 95,
      wheelbaseMm: 1163,
      bbDropMm: 42,
    },
    cuadroDesc: "Orbea Oiz Carbon OMX, Fiberlink, Boost, BSA, UFO, I-line shock, 120mm travel, thru axle 12x148mm",
    horquillaDesc: "Fox 34 Float SC Factory 120 FIT4 Remote-Adj Push-Unlock QR15x110 Kashima",
    frenosDesc: "SRAM Level Ultimate Stealth 4-piston Hydraulic Disc",
    ruedasDesc: "Oquo Mountain Performance MP30LTD Carbon Tubeless Ready",
    cubiertasDesc: "Maxxis Rekon Race 2.40 WT 120 TPI Exo TLR",
    manillarDesc: "OC Mountain Performance MP10 Carbon, Width 760, Sweep 9",
    potenciaDesc: "OC Mountain Performance MP10 Alu SL, -10º",
    tijaDesc: "Fox Transfer SL Factory Kashima 31.6mm Dropper",
    sillinDesc: "Selle Italia SLR Boost Fill Carbon Rail",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/oiz/cat/oiz-m-ltd-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-oiz-m-pro-2025",
    modelName: "Oiz M-PRO",
    family: "Oiz",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 6299,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 10.4,
    clearanceMm: 62,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano XTR M9100 / XT M8100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "34T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 605,
      reachMm: 450,
      headTubeAngleDeg: 67.0,
      chainstayLengthMm: 432,
      seatTubeAngleDeg: 76.5,
      topTubeLengthMm: 598,
      seatTubeLengthMm: 432,
      headTubeLengthMm: 95,
      wheelbaseMm: 1163,
      bbDropMm: 42,
    },
    cuadroDesc: "Orbea Oiz Carbon OMX, Fiberlink, Boost, BSA, UFO, I-line shock, 120mm travel",
    horquillaDesc: "Fox 34 Float SC Factory 120 FIT4 Remote Kashima, QR15x110",
    frenosDesc: "Shimano XT M8100 Hydraulic Disc",
    ruedasDesc: "Oquo Mountain Performance MP30TEAM Carbon Tubeless Ready",
    cubiertasDesc: "Maxxis Rekon Race 2.40 WT 120 TPI Exo TLR",
    manillarDesc: "OC Mountain Performance MP10 Carbon, Width 760",
    potenciaDesc: "OC Mountain Performance MP20, -8º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Selle Italia SLR Boost Titanio Rail",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/oiz/cat/oiz-m-pro-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-oiz-m10-2025",
    modelName: "Oiz M10",
    family: "Oiz",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 5499,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 10.7,
    clearanceMm: 62,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano XT M8100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "34T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 605,
      reachMm: 450,
      headTubeAngleDeg: 67.0,
      chainstayLengthMm: 432,
      seatTubeAngleDeg: 76.5,
      topTubeLengthMm: 598,
      seatTubeLengthMm: 432,
      headTubeLengthMm: 95,
      wheelbaseMm: 1163,
      bbDropMm: 42,
    },
    cuadroDesc: "Orbea Oiz Carbon OMR, Fiberlink, Boost, BSA, UFO, I-line shock, 120mm travel",
    horquillaDesc: "Fox 34 Float SC Factory 120 FIT4 Remote Kashima, QR15x110",
    frenosDesc: "Shimano XT M8100 Hydraulic Disc",
    ruedasDesc: "Oquo Mountain Performance MP30TEAM Carbon Tubeless Ready",
    cubiertasDesc: "Maxxis Rekon Race 2.40 WT 120 TPI Exo TLR",
    manillarDesc: "OC Mountain Performance MP21 Alu SL, Width 760",
    potenciaDesc: "OC Mountain Performance MP21, -6º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Fizik Taiga S-alloy rail",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/oiz/cat/oiz-m10-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-oiz-m20-2025",
    modelName: "Oiz M20",
    family: "Oiz",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 4799,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 11.2,
    clearanceMm: 62,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "sram",
      name: "SRAM GX Eagle AXS Transmission",
      isElectronic: true,
      speedCount: 12,
      chainrings: "32T",
      cassette: "10-52T",
    },
    geometry: {
      stackMm: 605,
      reachMm: 450,
      headTubeAngleDeg: 67.0,
      chainstayLengthMm: 432,
      seatTubeAngleDeg: 76.5,
      topTubeLengthMm: 598,
      seatTubeLengthMm: 432,
      headTubeLengthMm: 95,
      wheelbaseMm: 1163,
      bbDropMm: 42,
    },
    cuadroDesc: "Orbea Oiz Carbon OMR, Fiberlink, Boost, BSA, UFO, I-line shock, 120mm travel",
    horquillaDesc: "Fox 34 Float SC Performance 120 Grip Remote, QR15x110",
    frenosDesc: "Shimano M6100 Hydraulic Disc",
    ruedasDesc: "Oquo Mountain Performance MP28PRO Alloy Tubeless Ready",
    cubiertasDesc: "Maxxis Rekon Race 2.40 WT 120 TPI Exo TLR",
    manillarDesc: "OC Mountain Performance MP30, Width 760",
    potenciaDesc: "OC Mountain Performance MP21, -6º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Fizik Taiga S-alloy rail",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/oiz/cat/oiz-m20-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-oiz-m30-2025",
    modelName: "Oiz M30",
    family: "Oiz",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 3999,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 11.6,
    clearanceMm: 62,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano SLX M7100 / Deore M6100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "32T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 605,
      reachMm: 450,
      headTubeAngleDeg: 67.0,
      chainstayLengthMm: 432,
      seatTubeAngleDeg: 76.5,
      topTubeLengthMm: 598,
      seatTubeLengthMm: 432,
      headTubeLengthMm: 95,
      wheelbaseMm: 1163,
      bbDropMm: 42,
    },
    cuadroDesc: "Orbea Oiz Carbon OMR, Fiberlink, Boost, BSA, UFO, I-line shock, 120mm travel",
    horquillaDesc: "Fox 34 Float SC Performance 120 Grip Remote, QR15x110",
    frenosDesc: "Shimano M6100 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 29, 25c, 32H",
    cubiertasDesc: "Maxxis Rekon Race 2.40 WT 120 TPI Exo TLR",
    manillarDesc: "OC Mountain Performance MP30, Width 760",
    potenciaDesc: "OC Mountain Performance MP21, -6º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Selle Italia Model X FecAlloy Rail",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/oiz/cat/oiz-m30-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-oiz-h10-2025",
    modelName: "Oiz H10",
    family: "Oiz",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 3299,
    frameMaterial: "aluminum",
    forkMaterial: "suspension",
    weightKg: 12.6,
    clearanceMm: 62,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano XT M8100 / SLX M7100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "32T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 605,
      reachMm: 450,
      headTubeAngleDeg: 67.0,
      chainstayLengthMm: 432,
      seatTubeAngleDeg: 76.5,
      topTubeLengthMm: 598,
      seatTubeLengthMm: 432,
      headTubeLengthMm: 95,
      wheelbaseMm: 1163,
      bbDropMm: 42,
    },
    cuadroDesc: "Orbea Oiz Hydro High Polished, Alloy link, Boost, BSA, UFO, I-line shock, 120mm travel",
    horquillaDesc: "Fox 34 Float SC Performance 120 Grip Remote, QR15x110",
    frenosDesc: "Shimano M6100 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 29, 25c, 32H",
    cubiertasDesc: "Maxxis Rekon Race 2.40 WT 120 TPI Exo TLR",
    manillarDesc: "OC Mountain Performance MP30, Width 760",
    potenciaDesc: "OC Mountain Performance MP21, -6º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Selle Italia Model X FecAlloy",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/oiz/cat/oiz-h10-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-oiz-h30-2025",
    modelName: "Oiz H30",
    family: "Oiz",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 2499,
    frameMaterial: "aluminum",
    forkMaterial: "suspension",
    weightKg: 13.1,
    clearanceMm: 62,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano Deore M6100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "32T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 605,
      reachMm: 450,
      headTubeAngleDeg: 67.0,
      chainstayLengthMm: 432,
      seatTubeAngleDeg: 76.5,
      topTubeLengthMm: 598,
      seatTubeLengthMm: 432,
      headTubeLengthMm: 95,
      wheelbaseMm: 1163,
      bbDropMm: 42,
    },
    cuadroDesc: "Orbea Oiz Hydro High Polished, Boost, BSA, 120mm travel",
    horquillaDesc: "Fox 32 Float Rhythm 120 Remote QR15x110",
    frenosDesc: "Shimano MT201 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 29, 25c, 32H",
    cubiertasDesc: "Maxxis Ikon 2.20 FB 60 TPI Dual",
    manillarDesc: "OC Mountain Performance MP30, Width 760",
    potenciaDesc: "OC Mountain Performance MP21, -6º",
    tijaDesc: "Alloy, 31.6mm, Setback 0",
    sillinDesc: "Selle Italia Model X",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/oiz/cat/oiz-h30-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },

  // ==========================================
  // MONTAÑA - ALMA (XC Rígida / Hardtail)
  // ==========================================
  {
    idSlug: "orbea-alma-m-pro-2025",
    modelName: "Alma M-PRO",
    family: "Alma",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 5499,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 8.9,
    clearanceMm: 60,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano XTR M9100 / XT M8100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "34T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 615,
      reachMm: 426,
      headTubeAngleDeg: 68.0,
      chainstayLengthMm: 430,
      seatTubeAngleDeg: 74.5,
      topTubeLengthMm: 602,
      seatTubeLengthMm: 445,
      headTubeLengthMm: 95,
      wheelbaseMm: 1115,
      bbDropMm: 61,
    },
    cuadroDesc: "Orbea Alma Carbon OMX, Boost 12x148, PF BB, Internal cable routing",
    horquillaDesc: "Fox 32 Float SC Factory 100 FIT4 Remote-Adj Push-Unlock QR15x110 Kashima",
    frenosDesc: "Shimano XT M8100 Hydraulic Disc",
    ruedasDesc: "Oquo Mountain Performance MP30TEAM Carbon",
    cubiertasDesc: "Maxxis Rekon Race 2.35 120 TPI Exo TLR",
    manillarDesc: "OC Mountain Performance MP10 Carbon, Width 760",
    potenciaDesc: "OC Mountain Performance MP20, -8º",
    tijaDesc: "OC Performance XP10 Carbon, 27.2mm",
    sillinDesc: "Selle Italia SLR Boost Titanio Rail",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/alma/cat/alma-m-pro-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-alma-m30-2025",
    modelName: "Alma M30",
    family: "Alma",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 2199,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 11.2,
    clearanceMm: 60,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano SLX M7100 / Deore M6100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "32T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 615,
      reachMm: 426,
      headTubeAngleDeg: 68.0,
      chainstayLengthMm: 430,
      seatTubeAngleDeg: 74.5,
      topTubeLengthMm: 602,
      seatTubeLengthMm: 445,
      headTubeLengthMm: 95,
      wheelbaseMm: 1115,
      bbDropMm: 61,
    },
    cuadroDesc: "Orbea Alma Carbon OMR, Boost 12x148, PF BB, Internal cable routing",
    horquillaDesc: "RockShox Judy Silver TK Remote Solo Air 100 QR15x110 Boost",
    frenosDesc: "Shimano MT201 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 29, 25c, 32H",
    cubiertasDesc: "Maxxis Rekon Race 2.35 60 TPI Exo TLR",
    manillarDesc: "OC Mountain Performance MP30, Width 760",
    potenciaDesc: "OC Mountain Performance MP21, -6º",
    tijaDesc: "Alloy, 27.2mm, Setback 0",
    sillinDesc: "Selle Italia Model X",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/alma/cat/alma-m30-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-alma-h30-2025",
    modelName: "Alma H30",
    family: "Alma",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 1099,
    frameMaterial: "aluminum",
    forkMaterial: "suspension",
    weightKg: 12.8,
    clearanceMm: 60,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano Deore M5100",
      isElectronic: false,
      speedCount: 11,
      chainrings: "32T",
      cassette: "11-51T",
    },
    geometry: {
      stackMm: 615,
      reachMm: 426,
      headTubeAngleDeg: 68.0,
      chainstayLengthMm: 430,
      seatTubeAngleDeg: 74.5,
      topTubeLengthMm: 602,
      seatTubeLengthMm: 445,
      headTubeLengthMm: 95,
      wheelbaseMm: 1115,
      bbDropMm: 61,
    },
    cuadroDesc: "Orbea Alma Hydro Alloy, Boost 12x148, BSA BB, Internal cable routing",
    horquillaDesc: "SR Suntour Raidon 32 RLR 100mm QR15x110 Boost",
    frenosDesc: "Shimano MT201 Hydraulic Disc",
    ruedasDesc: "Mach1 Klixx 23c Tubeless Ready",
    cubiertasDesc: "Maxxis Ikon 2.20 FB 60 TPI Dual",
    manillarDesc: "OC Mountain Performance MP30, Width 760",
    potenciaDesc: "Alloy 7º",
    tijaDesc: "Alloy, 27.2mm",
    sillinDesc: "Selle Royal 2058 DRN",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/alma/cat/alma-h30-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },

  // ==========================================
  // MONTAÑA - OCCAM (Trail 140mm / 150mm)
  // ==========================================
  {
    idSlug: "orbea-occam-sl-m10-2025",
    modelName: "Occam SL M10",
    family: "Occam",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 5999,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 12.2,
    clearanceMm: 62,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano XT M8100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "32T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 618,
      reachMm: 465,
      headTubeAngleDeg: 65.5,
      chainstayLengthMm: 440,
      seatTubeAngleDeg: 78.0,
      topTubeLengthMm: 595,
      seatTubeLengthMm: 415,
      headTubeLengthMm: 110,
      wheelbaseMm: 1205,
      bbDropMm: 35,
    },
    cuadroDesc: "Orbea Occam OMR Carbon 140mm travel, Concentric Boost 12x148, LOCKR internal storage",
    horquillaDesc: "Fox 34 Float Factory 140 FIT4 Remote-Adj QR15x110 Kashima",
    frenosDesc: "Shimano XT M8120 4-Piston Hydraulic Disc",
    ruedasDesc: "Oquo Mountain Control MC32TEAM Carbon Tubeless Ready",
    cubiertasDesc: "Maxxis Dissector 2.40 WT 60 TPI 3C MaxxTerra Exo TLR",
    manillarDesc: "OC Mountain Control MC10 Carbon, Rise 20, Width 800",
    potenciaDesc: "OC Mountain Control MC20, 0º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Fizik Terra Ridon X5 145mm",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/occam/cat/occam-sl-m10-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-occam-sl-h30-2025",
    modelName: "Occam SL H30",
    family: "Occam",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 2799,
    frameMaterial: "aluminum",
    forkMaterial: "suspension",
    weightKg: 14.3,
    clearanceMm: 62,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano Deore M6100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "32T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 618,
      reachMm: 465,
      headTubeAngleDeg: 65.5,
      chainstayLengthMm: 440,
      seatTubeAngleDeg: 78.0,
      topTubeLengthMm: 595,
      seatTubeLengthMm: 415,
      headTubeLengthMm: 110,
      wheelbaseMm: 1205,
      bbDropMm: 35,
    },
    cuadroDesc: "Orbea Occam Hydro High Polished 140mm travel, Concentric Boost 12x148",
    horquillaDesc: "Marzocchi Bomber Z2 140mm QR15x110",
    frenosDesc: "Shimano MT201 Hydraulic Disc",
    ruedasDesc: "Alloy, Tubeless, 29, 29c, 32H",
    cubiertasDesc: "Maxxis Dissector 2.40 WT 60 TPI Exo TLR",
    manillarDesc: "OC Mountain Control MC30, Rise 20, Width 800",
    potenciaDesc: "OC Mountain Control MC20, 0º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Selle Italia Model X",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/occam/cat/occam-sl-h30-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },

  // ==========================================
  // MONTAÑA - RALLON (Enduro 170mm/160mm)
  // ==========================================
  {
    idSlug: "orbea-rallon-m-team-2025",
    modelName: "Rallon M-TEAM",
    family: "Rallon",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 6999,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 14.6,
    clearanceMm: 64,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano XT M8100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "32T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 632,
      reachMm: 460,
      headTubeAngleDeg: 64.0,
      chainstayLengthMm: 442,
      seatTubeAngleDeg: 77.5,
      topTubeLengthMm: 605,
      seatTubeLengthMm: 415,
      headTubeLengthMm: 115,
      wheelbaseMm: 1235,
      bbDropMm: 28,
    },
    cuadroDesc: "Orbea Rallon OMR Carbon 167mm travel, Concentric Boost 12x148, LOCKR internal storage",
    horquillaDesc: "Fox 38 Float Factory 170 Grip2 QR15x110 Kashima",
    frenosDesc: "Shimano XT M8120 4-Piston Hydraulic Disc",
    ruedasDesc: "Oquo Mountain Control MC32TEAM Carbon Tubeless Ready",
    cubiertasDesc: "Maxxis Assegai 2.50 WT FB 120 TPI 3C MaxxTerra EXO+ TR",
    manillarDesc: "OC Mountain Control MC10 Carbon, Rise 20, Width 800",
    potenciaDesc: "OC Mountain Control MC20, 0º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Fizik Terra Ridon X5 145mm",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/rallon/cat/rallon-m-team-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-rallon-m20-2025",
    modelName: "Rallon M20",
    family: "Rallon",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 4999,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 15.2,
    clearanceMm: 64,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano SLX M7100 / Deore M6100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "32T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 632,
      reachMm: 460,
      headTubeAngleDeg: 64.0,
      chainstayLengthMm: 442,
      seatTubeAngleDeg: 77.5,
      topTubeLengthMm: 605,
      seatTubeLengthMm: 415,
      headTubeLengthMm: 115,
      wheelbaseMm: 1235,
      bbDropMm: 28,
    },
    cuadroDesc: "Orbea Rallon OMR Carbon 167mm travel, Concentric Boost 12x148, LOCKR storage",
    horquillaDesc: "Fox 38 Float Performance 170 Grip 3-Pos QR15x110",
    frenosDesc: "Shimano M6120 4-Piston Hydraulic Disc",
    ruedasDesc: "Race Face AR 30c Tubeless Ready",
    cubiertasDesc: "Maxxis Assegai 2.50 WT FB 60 TPI 3C MaxxTerra EXO+ TR",
    manillarDesc: "OC Mountain Control MC30, Rise 20, Width 800",
    potenciaDesc: "OC Mountain Control MC20, 0º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Fizik Terra Ridon X5",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/rallon/cat/rallon-m20-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },

  // ==========================================
  // MONTAÑA - LAUFEY (Hardtail Trail 140mm)
  // ==========================================
  {
    idSlug: "orbea-laufey-h-ltd-2025",
    modelName: "Laufey H-LTD",
    family: "Laufey",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 2499,
    frameMaterial: "aluminum",
    forkMaterial: "suspension",
    weightKg: 13.5,
    clearanceMm: 65,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano XT M8100 / SLX M7100",
      isElectronic: false,
      speedCount: 12,
      chainrings: "32T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 635,
      reachMm: 445,
      headTubeAngleDeg: 64.5,
      chainstayLengthMm: 435,
      seatTubeAngleDeg: 77.0,
      topTubeLengthMm: 610,
      seatTubeLengthMm: 415,
      headTubeLengthMm: 110,
      wheelbaseMm: 1180,
      bbDropMm: 45,
    },
    cuadroDesc: "Orbea Laufey Hydro Triple Butted 29 Boost 12x148 with LOCKR internal downtube storage",
    horquillaDesc: "Fox 34 Float Performance 140 Grip 3-Pos QR15x110",
    frenosDesc: "Shimano M6120 4-Piston Hydraulic Disc",
    ruedasDesc: "Race Face AR 30c Tubeless Ready",
    cubiertasDesc: "Maxxis Dissector 2.60 WT 60 TPI Exo TLR",
    manillarDesc: "OC Mountain Control MC30, Rise 20, Width 800",
    potenciaDesc: "OC Mountain Control MC20, 0º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Fizik Ridon X5",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/laufey/cat/laufey-h-ltd-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-laufey-h30-2025",
    modelName: "Laufey H30",
    family: "Laufey",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 1499,
    frameMaterial: "aluminum",
    forkMaterial: "suspension",
    weightKg: 14.4,
    clearanceMm: 65,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano Deore M5100",
      isElectronic: false,
      speedCount: 11,
      chainrings: "32T",
      cassette: "11-51T",
    },
    geometry: {
      stackMm: 635,
      reachMm: 445,
      headTubeAngleDeg: 64.5,
      chainstayLengthMm: 435,
      seatTubeAngleDeg: 77.0,
      topTubeLengthMm: 610,
      seatTubeLengthMm: 415,
      headTubeLengthMm: 110,
      wheelbaseMm: 1180,
      bbDropMm: 45,
    },
    cuadroDesc: "Orbea Laufey Hydro Triple Butted 29 Boost 12x148 with LOCKR storage",
    horquillaDesc: "RockShox Recon Silver RL 140mm Solo Air QR15x110 Boost",
    frenosDesc: "Shimano MT201 Hydraulic Disc",
    ruedasDesc: "Mach1 Klixx 23c Tubeless Ready",
    cubiertasDesc: "Maxxis Dissector 2.60 WT 60 TPI Exo TLR",
    manillarDesc: "OC Mountain Control MC30, Width 800",
    potenciaDesc: "Alloy 35mm",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Selle Royal 2058 DRN",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/laufey/cat/laufey-h30-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },

  // ==========================================
  // MONTAÑA - ONNA (Iniciación XC / Sport)
  // ==========================================
  {
    idSlug: "orbea-onna-10-2025",
    modelName: "Onna 10",
    family: "Onna",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 899,
    frameMaterial: "aluminum",
    forkMaterial: "suspension",
    weightKg: 13.8,
    clearanceMm: 57,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano Deore M5100",
      isElectronic: false,
      speedCount: 11,
      chainrings: "32T",
      cassette: "11-51T",
    },
    geometry: {
      stackMm: 620,
      reachMm: 418,
      headTubeAngleDeg: 68.5,
      chainstayLengthMm: 440,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 595,
      seatTubeLengthMm: 445,
      headTubeLengthMm: 105,
      wheelbaseMm: 1115,
      bbDropMm: 65,
    },
    cuadroDesc: "Orbea Onna Alloy, Dropout 9x135, BSA BB, Internal cable routing",
    horquillaDesc: "RockShox Judy Silver TK Solo Air 100mm QR",
    frenosDesc: "Shimano MT201 Hydraulic Disc",
    ruedasDesc: "Orbea Black Rock 23c Disc",
    cubiertasDesc: "Kenda K1153 2.35 22TPI",
    manillarDesc: "Alloy Flat 31.8mm 720mm",
    potenciaDesc: "Alloy 31.8mm 7º",
    tijaDesc: "Alloy 27.2mm Offset 0",
    sillinDesc: "Selle Royal 2058 DRN",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/onna/cat/onna-10-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
  {
    idSlug: "orbea-onna-20-2025",
    modelName: "Onna 20",
    family: "Onna",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 799,
    frameMaterial: "aluminum",
    forkMaterial: "suspension",
    weightKg: 14.1,
    clearanceMm: 57,
    integratedCockpit: false,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano Deore M4100",
      isElectronic: false,
      speedCount: 10,
      chainrings: "32T",
      cassette: "11-46T",
    },
    geometry: {
      stackMm: 620,
      reachMm: 418,
      headTubeAngleDeg: 68.5,
      chainstayLengthMm: 440,
      seatTubeAngleDeg: 73.5,
      topTubeLengthMm: 595,
      seatTubeLengthMm: 445,
      headTubeLengthMm: 105,
      wheelbaseMm: 1115,
      bbDropMm: 65,
    },
    cuadroDesc: "Orbea Onna Alloy, Dropout 9x135, BSA BB, Internal cable routing",
    horquillaDesc: "SR Suntour XCR Air LO 100mm QR",
    frenosDesc: "Shimano MT200 Hydraulic Disc",
    ruedasDesc: "Orbea Black Rock 23c Disc",
    cubiertasDesc: "Kenda K1153 2.35 22TPI",
    manillarDesc: "Alloy Flat 31.8mm 720mm",
    potenciaDesc: "Alloy 31.8mm 7º",
    tijaDesc: "Alloy 27.2mm Offset 0",
    sillinDesc: "Selle Royal 2058 DRN",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/onna/cat/onna-20-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },

  // ==========================================
  // MONTAÑA - RISE (e-MTB Ligera Shimano EP801-RS)
  // ==========================================
  {
    idSlug: "orbea-rise-sl-m10-2025",
    modelName: "Rise SL M10",
    family: "Rise",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 7999,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 16.4,
    clearanceMm: 64,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano XT M8100 / EP801-RS",
      isElectronic: false,
      speedCount: 12,
      chainrings: "32T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 622,
      reachMm: 450,
      headTubeAngleDeg: 65.5,
      chainstayLengthMm: 445,
      seatTubeAngleDeg: 77.0,
      topTubeLengthMm: 595,
      seatTubeLengthMm: 415,
      headTubeLengthMm: 110,
      wheelbaseMm: 1210,
      bbDropMm: 33,
    },
    cuadroDesc: "Orbea Rise SL OMR Carbon 140mm travel, Shimano EP801-RS motor, integrated 420Wh / 630Wh battery, Concentric Boost 12x148",
    horquillaDesc: "Fox 34 Float Factory 140 FIT4 Kashima, QR15x110",
    frenosDesc: "Shimano XT M8120 4-Piston Hydraulic Disc",
    ruedasDesc: "Oquo Mountain Control MC32TEAM Carbon Tubeless Ready",
    cubiertasDesc: "Maxxis Dissector 2.40 WT 60 TPI 3C MaxxTerra Exo TLR",
    manillarDesc: "OC Mountain Control MC10 Carbon, Width 800",
    potenciaDesc: "OC Mountain Control MC20, 0º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Fizik Terra Ridon X5",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/rise/cat/rise-sl-m10-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },

  // ==========================================
  // MONTAÑA - WILD (e-MTB Enduro Bosch CX)
  // ==========================================
  {
    idSlug: "orbea-wild-m-team-2025",
    modelName: "Wild M-TEAM",
    family: "Wild",
    year: 2025,
    discipline: "mtb",
    categoryFile: "montana",
    price: 8999,
    frameMaterial: "carbon",
    forkMaterial: "suspension",
    weightKg: 20.9,
    clearanceMm: 65,
    integratedCockpit: true,
    bikepackingMounts: false,
    groupset: {
      brand: "shimano",
      name: "Shimano XT M8100 / Bosch CX",
      isElectronic: false,
      speedCount: 12,
      chainrings: "34T",
      cassette: "10-51T",
    },
    geometry: {
      stackMm: 638,
      reachMm: 455,
      headTubeAngleDeg: 64.0,
      chainstayLengthMm: 448,
      seatTubeAngleDeg: 77.5,
      topTubeLengthMm: 605,
      seatTubeLengthMm: 415,
      headTubeLengthMm: 115,
      wheelbaseMm: 1245,
      bbDropMm: 25,
    },
    cuadroDesc: "Orbea Wild Carbon OMR 160mm travel, Bosch Performance Line CX, integrated 750Wh battery, Boost 12x148",
    horquillaDesc: "Fox 38 Float Factory 160 Grip2 QR15x110 Kashima",
    frenosDesc: "Shimano XT M8120 4-Piston Hydraulic Disc",
    ruedasDesc: "Oquo Mountain Control MC32TEAM e-MTB Tubeless Ready",
    cubiertasDesc: "Maxxis Minion DHF 2.60 120 TPI 3C MaxxTerra Exo+ TR",
    manillarDesc: "OC Mountain Control MC10 Carbon, Width 800",
    potenciaDesc: "OC Mountain Control MC20, 0º",
    tijaDesc: "OC Mountain Control MC21 Dropper, 31.6mm",
    sillinDesc: "Fizik Aidon X5 145mm",
    officialUrl: "https://www.orbea.com/es-es/bicicletas/montana/wild/cat/wild-m-team-2025",
    officialImageUrl: "https://cdn.deporvillage.com/cdn-cgi/image/f=auto,q=75,fit=contain,background=white/product-vertical/orb-s10749aj_001.jpg",
  },
];

export function buildOrbeaBike(def: OrbeaModelDef): BikeProduct {
  const { minRatio, maxRatio } = calculateRatios(def.groupset.chainrings, def.groupset.cassette);

  const stackReachRatio = Number((def.geometry.stackMm / def.geometry.reachMm).toFixed(2));

  const highlights = [
    `Cuadro oficial Orbea ${def.frameMaterial.toUpperCase()}`,
    `Grupo ${def.groupset.name} (${def.groupset.speedCount}v)`,
    `Paso de rueda hasta ${def.clearanceMm} mm`,
  ];
  if (def.groupset.isElectronic) highlights.push("Cambio electrónico Di2 / AXS");
  if (def.integratedCockpit) highlights.push("Cockpit integrado y cableado interno ICR");
  if (def.bikepackingMounts) highlights.push("Anclajes para bolsas / almacenamiento LOCKR");

  return {
    id: def.idSlug,
    brand: "Orbea",
    model: def.modelName,
    year: def.year,
    discipline: def.discipline,
    officialUrl: def.officialUrl,
    officialImageUrl: def.officialImageUrl,
    msrpEur: def.originalMsrp || def.price,
    currentPriceEur: def.price,
    discountPercentage: def.originalMsrp && def.originalMsrp > def.price
      ? Math.round(((def.originalMsrp - def.price) / def.originalMsrp) * 100)
      : 0,
    isOutlet: !!(def.originalMsrp && def.originalMsrp > def.price),
    frameMaterial: def.frameMaterial,
    forkMaterial: def.forkMaterial,
    weightKg: def.weightKg,
    weightSizeReference: def.weightKg ? "M" : undefined,
    maxTireClearanceMm: def.clearanceMm,
    integratedCockpit: def.integratedCockpit,
    bikepackingMounts: def.bikepackingMounts,
    groupset: {
      brand: def.groupset.brand,
      name: def.groupset.name,
      isElectronic: def.groupset.isElectronic,
      speedCount: def.groupset.speedCount,
      chainrings: def.groupset.chainrings,
      cassette: def.groupset.cassette,
      minGearRatio: minRatio,
      maxGearRatio: maxRatio,
    },
    geometry: {
      stackMm: def.geometry.stackMm,
      reachMm: def.geometry.reachMm,
      stackReachRatio,
      headTubeAngleDeg: def.geometry.headTubeAngleDeg,
      chainstayLengthMm: def.geometry.chainstayLengthMm,
      seatTubeAngleDeg: def.geometry.seatTubeAngleDeg,
      topTubeLengthMm: def.geometry.topTubeLengthMm,
      seatTubeLengthMm: def.geometry.seatTubeLengthMm,
      headTubeLengthMm: def.geometry.headTubeLengthMm,
      wheelbaseMm: def.geometry.wheelbaseMm,
      bbDropMm: def.geometry.bbDropMm,
    },
    description: `Bicicleta oficial Orbea ${def.modelName} (${def.year}) gama ${def.family} de categoría ${def.discipline}. Diseñada en Mallabia con cuadro ${def.frameMaterial} y montaje oficial ${def.groupset.name}.`.slice(0, 1000),
    highlights,
    brakes: def.frenosDesc,
    wheels: def.ruedasDesc,
    tires: def.cubiertasDesc,
    detailedSpecs: [
      {
        category: "Cuadro y Horquilla",
        items: [
          { label: "Cuadro", value: def.cuadroDesc },
          { label: "Horquilla", value: def.horquillaDesc },
        ],
      },
      {
        category: "Transmisión",
        items: [
          { label: "Grupo", value: def.groupset.name },
          { label: "Desarrollo Platos", value: def.groupset.chainrings },
          { label: "Cassette", value: def.groupset.cassette },
        ],
      },
      {
        category: "Frenos",
        items: [{ label: "Frenos", value: def.frenosDesc }],
      },
      {
        category: "Ruedas y Neumáticos",
        items: [
          { label: "Ruedas", value: def.ruedasDesc },
          { label: "Cubiertas", value: def.cubiertasDesc },
        ],
      },
      {
        category: "Componentes",
        items: [
          { label: "Manillar", value: def.manillarDesc },
          { label: "Potencia", value: def.potenciaDesc },
          { label: "Tija de Sillín", value: def.tijaDesc },
          { label: "Sillín", value: def.sillinDesc },
        ],
      },
    ],
  };
}

export function generateOrbeaCatalog() {
  console.log(`\n🇪🇸 [Orbea Official Generator] Generando ${ORBEA_MODELS.length} modelos oficiales de Orbea...\n`);

  const catalogs: Record<string, BikeProduct[]> = {
    carretera: fs.existsSync(CARRETERA_FILE) ? JSON.parse(fs.readFileSync(CARRETERA_FILE, "utf-8")) : [],
    gravel: fs.existsSync(GRAVEL_FILE) ? JSON.parse(fs.readFileSync(GRAVEL_FILE, "utf-8")) : [],
    montana: fs.existsSync(MONTANA_FILE) ? JSON.parse(fs.readFileSync(MONTANA_FILE, "utf-8")) : [],
  };

  const linksByCat = {
    carretera: [] as string[],
    gravel: [] as string[],
    montana: [] as string[],
  };

  let validCount = 0;

  for (const def of ORBEA_MODELS) {
    const bike = buildOrbeaBike(def);
    const parsed = BikeProductSchema.safeParse(bike);

    if (!parsed.success) {
      console.error(`❌ Error Zod en Orbea ${def.modelName}:`, JSON.stringify(parsed.error.format(), null, 2));
      continue;
    }

    const catList = catalogs[def.categoryFile];
    const existingIdx = catList.findIndex((b) => b.id === bike.id || b.officialUrl === bike.officialUrl);

    if (existingIdx >= 0) {
      catList[existingIdx] = parsed.data;
      console.log(`  🔄 [Actualizado] Orbea ${bike.model} (${bike.id}) en ${def.categoryFile}.json`);
    } else {
      catList.push(parsed.data);
      console.log(`  ✅ [Añadido] Orbea ${bike.model} (${bike.id}) en ${def.categoryFile}.json`);
    }

    linksByCat[def.categoryFile].push(def.officialUrl);
    validCount++;
  }

  // Guardar catálogos
  fs.writeFileSync(CARRETERA_FILE, JSON.stringify(catalogs.carretera, null, 2), "utf-8");
  fs.writeFileSync(GRAVEL_FILE, JSON.stringify(catalogs.gravel, null, 2), "utf-8");
  fs.writeFileSync(MONTANA_FILE, JSON.stringify(catalogs.montana, null, 2), "utf-8");

  // Escribir links/orbea.txt con todos los enlaces oficiales generados
  const linksContent: string[] = [
    "# ==============================================================================",
    "# BIKEFINDER.ES - ENLACES OFICIALES: ORBEA (Mallabia, España)",
    "# ==============================================================================",
    "",
    `# ------------------------------------------------------------------------------`,
    `# CARRETERA (${linksByCat.carretera.length} modelos de serie: Orca OMX, Orca OMR, Orca Aero, Avant)`,
    `# ------------------------------------------------------------------------------`,
    ...linksByCat.carretera,
    "",
    `# ------------------------------------------------------------------------------`,
    `# GRAVEL & ALL-ROAD (${linksByCat.gravel.length} modelos de serie: Terra OMR, Terra Hydro)`,
    `# ------------------------------------------------------------------------------`,
    ...linksByCat.gravel,
    "",
    `# ------------------------------------------------------------------------------`,
    `# MONTAÑA (MTB) (${linksByCat.montana.length} modelos de serie: Oiz OMX/OMR/H, Alma OMX/OMR/H, Occam, Rallon, Laufey, Onna, Rise, Wild)`,
    `# ------------------------------------------------------------------------------`,
    ...linksByCat.montana,
    "",
  ];

  fs.writeFileSync(ORBEA_LINKS_FILE, linksContent.join("\n"), "utf-8");

  console.log(`\n🎉 Generación completada con éxito: ${validCount} modelos Orbea validados.`);
  console.log(`📁 Enlaces de registro guardados en: ${ORBEA_LINKS_FILE}`);
}

if (require.main === module) {
  generateOrbeaCatalog();
}
